# permissions for end users to view biosconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: biosconfig-viewer-role
rules:
- apiGroups:
  - bios.redhat.com
  resources:
  - biosconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bios.redhat.com
  resources:
  - biosconfigs/status
  verbs:
  - get
